version: '3.2'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.test
    volumes:
      - ./auth:/app

  videos:
    build:
      context: ./videos
      dockerfile: Dockerfile
    volumes:
      - ./videos:/videos


