version: '3.2'

services:
  nginx:
    build:
      context: ./webserver
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:8000
    depends_on:
      - auth
    networks:
      - union-network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=app
    networks:
      - union-network
    ports:
      - '5432:5432'
    restart: always

  auth:
    build:
      context: ./auth
    depends_on:
      - db
    networks:
      - union-network
    restart: always


volumes:
  postgres_volume:
  media_volume:
  static_volume:
  
networks:
  union-network:
    external: true
